### ISSUE TITLE
lack  file 

### ISSUE THREAD

**Issue by zhangjingling** [GYZHikari/semantic-cosegmentation#1]
we can not find the file "caffe-cedn-dev/examples ",   why ?

**Comment by GYZHikari** [comment]
do you have caffe？

**Comment by zhangjingling** [comment]
yes ,I have

**Comment by GYZHikari** [comment]
Hmmmm, we use the previous fcn network (not the same with currently caffe) maybe they are different (have not checked). If currently caffe does not contain it. Please try to make a new folder named examples.

**Comment by GYZHikari** [comment]
If you have any SNS ID you can tell me and we can discuss more details.

**Comment by zhangjingling** [comment]
E-mail ok? 13137730606@163.com

**Comment by GYZHikari** [comment]
Do you have qq?

**Comment by zhangjingling** [comment]
1536799740@qq.com

**Comment by AJ611** [comment]
Hi,

I have same issue here. There is a lot of folder address need to change in demo_segmantic_cosegment.m. I thought I just need to modified the address but I could not find where is demo_single_segment_resize.py and caffe-cedn-dev/examples. Did I missed something during installing caffe? I need your help.

Thank you.

**Comment by zhangjingling** [comment]
https://github.com/GYZHikari/semantic-cosegmentation/commits/master
有作者补充的文件，在https://github.com/GYZHikari/semantic-cosegmentation的点开comments ，即https://github.com/GYZHikari/semantic-cosegmentation/commits/master
